language: python
python:
    - "2.7"

before_install:
    - python -m pip install --upgrade pip

install:
    - pip install -U Sphinx
    - pip install -U travis-sphinx

script:
    - travis-sphinx build --source=example

after_success:
    - travis-sphinx deploy